title: "RAGWise"
description: "Read And Grow Wise: Book summaries with YouTube links"
baseurl: ""
url: "https://www.readandgrowwise.com"
theme: null
permalink: /:categories/:title.html
plugins:
  - jekyll-sitemap


paginate: 12
paginate_path: "/page/:num"
