title: "RAGWise"
description: "Read And Grow Wise: Book summaries of Best Books"
baseurl: ""
url: "https://www.readandgrowwise.com"
theme: null
permalink: /:categories/:title
plugins:
  - jekyll-sitemap


paginate: 12
paginate_path: "/page/:num"

plugins:
  - jekyll-paginate
